# Generated by Django 5.0.6 on 2025-01-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
